apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mehnajmart-ingress
  namespace: mehnaj-mart
spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mehnaj-mart-service
                port:
                  number: 80

