apiVersion: v1
data:
  PGDATA: L3Zhci9saWIvcG9zdGdyZXNxbC9kYXRhL3BnZGF0YQ==
  POSTGRES_DB: bWVobmFqbWFydF9kYg==
  POSTGRES_PASSWORD: TWVobmFqREJfOTlfU2VjdXJlUGFzczIwMjY=
  POSTGRES_USER: bWVobmFqbWFydF9hZG1pbg==
kind: Secret
metadata:
  name: postgresql-secret
  namespace: mehnaj-mart
